[project]
name = "03-streaming-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk[http-server]>=0.3.5",
    "openai-agents[litellm]>=0.3.0",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
